// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: perf.proto

#include "perf.pb.h"
#include "perf.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace proto {

static const char* PerfTest_method_names[] = {
  "/proto.PerfTest/Unary",
  "/proto.PerfTest/ClientStreaming",
  "/proto.PerfTest/ServerStreaming",
  "/proto.PerfTest/BidStreaming",
};

std::unique_ptr< PerfTest::Stub> PerfTest::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PerfTest::Stub> stub(new PerfTest::Stub(channel, options));
  return stub;
}

PerfTest::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Unary_(PerfTest_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ClientStreaming_(PerfTest_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_ServerStreaming_(PerfTest_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_BidStreaming_(PerfTest_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status PerfTest::Stub::Unary(::grpc::ClientContext* context, const ::proto::Message& request, ::proto::Message* response) {
  return ::grpc::internal::BlockingUnaryCall< ::proto::Message, ::proto::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Unary_, context, request, response);
}

void PerfTest::Stub::async::Unary(::grpc::ClientContext* context, const ::proto::Message* request, ::proto::Message* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::proto::Message, ::proto::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Unary_, context, request, response, std::move(f));
}

void PerfTest::Stub::async::Unary(::grpc::ClientContext* context, const ::proto::Message* request, ::proto::Message* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Unary_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::proto::Message>* PerfTest::Stub::PrepareAsyncUnaryRaw(::grpc::ClientContext* context, const ::proto::Message& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::proto::Message, ::proto::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Unary_, context, request);
}

::grpc::ClientAsyncResponseReader< ::proto::Message>* PerfTest::Stub::AsyncUnaryRaw(::grpc::ClientContext* context, const ::proto::Message& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUnaryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientWriter< ::proto::Message>* PerfTest::Stub::ClientStreamingRaw(::grpc::ClientContext* context, ::proto::Message* response) {
  return ::grpc::internal::ClientWriterFactory< ::proto::Message>::Create(channel_.get(), rpcmethod_ClientStreaming_, context, response);
}

void PerfTest::Stub::async::ClientStreaming(::grpc::ClientContext* context, ::proto::Message* response, ::grpc::ClientWriteReactor< ::proto::Message>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::proto::Message>::Create(stub_->channel_.get(), stub_->rpcmethod_ClientStreaming_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::proto::Message>* PerfTest::Stub::AsyncClientStreamingRaw(::grpc::ClientContext* context, ::proto::Message* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::proto::Message>::Create(channel_.get(), cq, rpcmethod_ClientStreaming_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::proto::Message>* PerfTest::Stub::PrepareAsyncClientStreamingRaw(::grpc::ClientContext* context, ::proto::Message* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::proto::Message>::Create(channel_.get(), cq, rpcmethod_ClientStreaming_, context, response, false, nullptr);
}

::grpc::ClientReader< ::proto::Message>* PerfTest::Stub::ServerStreamingRaw(::grpc::ClientContext* context, const ::proto::Message& request) {
  return ::grpc::internal::ClientReaderFactory< ::proto::Message>::Create(channel_.get(), rpcmethod_ServerStreaming_, context, request);
}

void PerfTest::Stub::async::ServerStreaming(::grpc::ClientContext* context, const ::proto::Message* request, ::grpc::ClientReadReactor< ::proto::Message>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::proto::Message>::Create(stub_->channel_.get(), stub_->rpcmethod_ServerStreaming_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::proto::Message>* PerfTest::Stub::AsyncServerStreamingRaw(::grpc::ClientContext* context, const ::proto::Message& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::proto::Message>::Create(channel_.get(), cq, rpcmethod_ServerStreaming_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::proto::Message>* PerfTest::Stub::PrepareAsyncServerStreamingRaw(::grpc::ClientContext* context, const ::proto::Message& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::proto::Message>::Create(channel_.get(), cq, rpcmethod_ServerStreaming_, context, request, false, nullptr);
}

::grpc::ClientReaderWriter< ::proto::Message, ::proto::Message>* PerfTest::Stub::BidStreamingRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::proto::Message, ::proto::Message>::Create(channel_.get(), rpcmethod_BidStreaming_, context);
}

void PerfTest::Stub::async::BidStreaming(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::proto::Message,::proto::Message>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::proto::Message,::proto::Message>::Create(stub_->channel_.get(), stub_->rpcmethod_BidStreaming_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::proto::Message, ::proto::Message>* PerfTest::Stub::AsyncBidStreamingRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::proto::Message, ::proto::Message>::Create(channel_.get(), cq, rpcmethod_BidStreaming_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::proto::Message, ::proto::Message>* PerfTest::Stub::PrepareAsyncBidStreamingRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::proto::Message, ::proto::Message>::Create(channel_.get(), cq, rpcmethod_BidStreaming_, context, false, nullptr);
}

PerfTest::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PerfTest_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PerfTest::Service, ::proto::Message, ::proto::Message, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PerfTest::Service* service,
             ::grpc::ServerContext* ctx,
             const ::proto::Message* req,
             ::proto::Message* resp) {
               return service->Unary(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PerfTest_method_names[1],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< PerfTest::Service, ::proto::Message, ::proto::Message>(
          [](PerfTest::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::proto::Message>* reader,
             ::proto::Message* resp) {
               return service->ClientStreaming(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PerfTest_method_names[2],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< PerfTest::Service, ::proto::Message, ::proto::Message>(
          [](PerfTest::Service* service,
             ::grpc::ServerContext* ctx,
             const ::proto::Message* req,
             ::grpc::ServerWriter<::proto::Message>* writer) {
               return service->ServerStreaming(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PerfTest_method_names[3],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< PerfTest::Service, ::proto::Message, ::proto::Message>(
          [](PerfTest::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::proto::Message,
             ::proto::Message>* stream) {
               return service->BidStreaming(ctx, stream);
             }, this)));
}

PerfTest::Service::~Service() {
}

::grpc::Status PerfTest::Service::Unary(::grpc::ServerContext* context, const ::proto::Message* request, ::proto::Message* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PerfTest::Service::ClientStreaming(::grpc::ServerContext* context, ::grpc::ServerReader< ::proto::Message>* reader, ::proto::Message* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PerfTest::Service::ServerStreaming(::grpc::ServerContext* context, const ::proto::Message* request, ::grpc::ServerWriter< ::proto::Message>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PerfTest::Service::BidStreaming(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::proto::Message, ::proto::Message>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace proto

